name: Harvest NERC P02

on:
  workflow_dispatch:
    inputs:
      collection-uri:
        description: 'NERC collection URI to harvest'
        required: true
        default: 'http://vocab.nerc.ac.uk/collection/P02/current/'
        type: string

jobs:
  harvest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: marine-term-translations/setup-harvest-action@main
        with:
          collection-uri: ${{ inputs.collection-uri || 'http://vocab.nerc.ac.uk/collection/P02/current/' }}
          token: ${{ secrets.GITHUB_TOKEN }}

